# Copyright (C) 2026 Blair Shevlin <blairshevlin@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Record of Revisions
#
# Date            Programmers                         Descriptions of Change
# ====         ================                       ======================
# 2026/05/06    Blair Shevlin                          Adapted from generate_figure4.R to generate panel E of Figure 1, which shows HDRS trajectories from baseline to month 6. 

# Source data is read from data/figures/figureExtended1_source_data.csv, which is generated by export_sourcedata.R.

rm(list = ls())

library(tidyverse)
library(fs)
library(here)
library(patchwork)
library(ggpubr)
library(RColorBrewer)
library(GGally)
library("ggnewscale")
library(scales)
library(ggrepel)


# Paths
res_dir = here::here("results/from_source_data")

# Load source data
source_data <- read.csv(here::here("data/figures/figureExtended1_source_data.csv"), stringsAsFactors = FALSE)

# Re-apply factor orderings
source_data$outcome_category <- factor(source_data$outcome_category,
                                       levels = c("Non-Responder","Responder","Remission"))

# Set colors
paired_cols <- RColorBrewer::brewer.pal(10, "Paired")                                       
reordered_cols <- c(paired_cols[9:10], paired_cols[1:8])

# ---- HDRS trajectories --------------------------------------------
trajectory <- source_data %>%
  filter(panel == "A") %>%
  arrange(as.numeric(idx)) %>%
  mutate(
    idx_lab = factor(
        ifelse(cohort == "RC+S",
              paste0("RC+S-", sprintf("%02d", as.numeric(idx))),
              paste0("PC-",   sprintf("%02d", as.numeric(idx)))),
        levels = c("RC+S-01","RC+S-02","RC+S-03","RC+S-04","RC+S-05",
                  "PC-06","PC-07","PC-08","PC-09","PC-10")
      ),
    sess_fig = factor(session,
                      levels = c("Baseline", "DBS", "Week 1", "Month 1", "Month 2",
                                 "Month 3", "Month 4", "Month 5", "Month 6"))
  )

fig.hdrs.trajectory <-
  ggplot(trajectory,aes(x = sess_fig, y = HDRS, color = idx_lab, group = idx_lab, shape = idx_lab)) +
  theme_pubr(base_size = 14) +
  geom_vline(xintercept = "DBS", linewidth = 2) +
  geom_hline(yintercept = 7, linetype = "dashed", linewidth = 0.75) +
  geom_line(data = ~ filter(.x, !is.na(HDRS)), linewidth = 1.5, alpha = .5, show.legend = FALSE) +
  geom_point(size = 3, stroke = 1.5, alpha = .75) +
  annotate("text", x = 0.5, y = 8, label = "Clinical Remission", size = 4.5, hjust = 0) +
  coord_cartesian(ylim = c(0, 32)) +
  scale_y_continuous(breaks = seq(0, 30, 10)) +
  scale_x_discrete(drop = FALSE) +
  scale_shape_manual(values = c(16,17,15,18,8,3,4,1,2,0))+
  scale_color_manual(values = setNames(reordered_cols,
  c("RC+S-01","RC+S-02","RC+S-03","RC+S-04","RC+S-05",
    "PC-06","PC-07","PC-08","PC-09","PC-10"))) +
  scale_fill_manual(values = setNames(reordered_cols,
  c("RC+S-01","RC+S-02","RC+S-03","RC+S-04","RC+S-05",
    "PC-06","PC-07","PC-08","PC-09","PC-10"))) +
  labs(x = element_blank(), y = "HDRS-17",
    shape = NULL, color = NULL, fill = NULL)+
  theme(legend.position = "right")  

extendedFig1 <- fig.hdrs.trajectory & theme(plot.tag = element_text(size = 22))

ggsave(file.path(res_dir, "Extended-Data_Figure1.png"),
       plot = extendedFig1, device = "png",
       width = 12, height = 8, dpi = 300)

