# Copyright (C) 2026 Blair Shevlin <blairshevlin@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Record of Revisions
#
# Date            Programmers                         Descriptions of Change
# ====         ================                       ======================
# 2026/05/06    Blair Shevlin                          Adapted from generate_figure4.R to generate panel E of Figure 1, which shows HDRS trajectories from baseline to month 6. 

# Source data is read from data/figures/figure1_panel_E_source_data.csv, which is generated by export_sourcedata.R.

rm(list = ls())

library(tidyverse)
library(fs)
library(here)
library(patchwork)
library(ggpubr)
library(RColorBrewer)
library(GGally)
library("ggnewscale")
library(scales)
library(ggrepel)


# Paths
res_dir = here::here("results/from_source_data")

# Load source data
source_data <- read.csv(here::here("data/figures/figure1_panel_E_source_data.csv"), stringsAsFactors = FALSE)

# Re-apply factor orderings
source_data$outcome_category <- factor(source_data$outcome_category,
                                       levels = c("Non-Responder","Responder","Remission"))

# ---- Panel E: HDRS trajectories --------------------------------------------
panel_E <- source_data %>%
  filter(panel == "E") %>%
  mutate(idx      = factor(idx),
         sess_fig = factor(session,
                           levels = c("Baseline","DBS","Week 1","Month 1","Month 2",
                                      "Month 3","Month 4","Month 5","Month 6")))

offset_data <- panel_E %>%
  filter(sess_fig %in% c("Baseline","Month 6")) %>%
  mutate(point_x_pos = ifelse(sess_fig == "Baseline", 1 + 0.1, 2 - 0.1),
         box_x_pos   = ifelse(sess_fig == "Baseline", 1 - 0.1, 2 + 0.1),
         sess_num    = ifelse(sess_fig == "Baseline", 1, 2))

fig.hdrs.change <-
  ggplot() +
  theme_pubr(base_size = 14) +
  geom_hline(yintercept = 7, linetype = "dashed", linewidth = 0.75) +
  annotate("text", x = 0.5, y = 8.5, label = "Clinical Remission", size = 5, hjust = 0) +
  geom_boxplot(data = offset_data,
               aes(x = box_x_pos, y = HDRS, group = sess_fig),
               linewidth = 1.1, outlier.alpha = 0, width = 0.15, show.legend = FALSE) +
  geom_line(data = offset_data,
            aes(x = point_x_pos, y = HDRS, group = idx),
            linewidth = 1.5, alpha = .25, color = "black") +
  geom_point(data = offset_data,
             aes(x = point_x_pos, y = HDRS, group = idx),
             size = 3, stroke = 1.5, alpha = .35, show.legend = FALSE) +
  coord_cartesian(ylim = c(0, 32)) +
  scale_x_continuous(breaks = c(1, 2), labels = c("Baseline","Month 6"), limits = c(0.5, 2.5)) +
  scale_y_continuous(breaks = seq(0, 30, 5)) +
  labs(x = element_blank(), y = "HDRS-17")

# ---- Assemble ---------------------------------------------------------------
fig.1E <- fig.hdrs.change + plot_layout(widths = c(1))

ggsave(file.path(res_dir, "figure1E.png"),
       plot = fig.1E, device = "png",
       width = 12, height = 8, dpi = 300)

ggsave(file.path(res_dir, "figure1E.pdf"),
       plot = fig.1E,
       device = "pdf",
       width = 12,
       height = 8,
       dpi = 300)
